// docs/src/examples/button/ButtonBasic.tsx
import { Button } from '@caioalfonso/kanso-react';
import { useState } from 'react';

export function ButtonBasic() {
  const [saving, setSaving] = useState(false);

  const save = async () => {
    setSaving(true);
    await new Promise((resolve) => setTimeout(resolve, 1200));
    setSaving(false);
  };

  return (
    <Button loading={saving} onClick={save}>
      Save changes
    </Button>
  );
}

// docs/src/examples/button/ButtonBasic.vue
<script setup lang="ts">
import { Button } from '@caioalfonso/kanso-vue';
import { ref } from 'vue';

const saving = ref(false);

async function save() {
  saving.value = true;
  await new Promise((resolve) => setTimeout(resolve, 1200));
  saving.value = false;
}
</script>

<template>
  <Button :loading="saving" @click="save">Save changes</Button>
</template>
