// docs/src/examples/field/FieldBasic.vue
<script setup lang="ts">
import { Field, Input } from '@caioalfonso/kanso-vue';
import { ref } from 'vue';

const email = ref('');
const invalid = ref(false);
</script>

<template>
  <Field :invalid="invalid" required>
    <template #label>Email</template>
    <template #description>We only use this to sign you in.</template>
    <template #error-text>Enter an email address.</template>

    <Input
      v-model="email"
      type="email"
      @blur="invalid = email === ''"
    />
  </Field>
</template>

// docs/src/examples/field/FieldBasic.tsx
import { Field, Input } from '@caioalfonso/kanso-react';
import { useState } from 'react';

export function FieldBasic() {
  const [email, setEmail] = useState('');
  const [invalid, setInvalid] = useState(false);

  return (
    <Field
      label="Email"
      description="We only use this to sign you in."
      errorText="Enter an email address."
      invalid={invalid}
      required
    >
      <Input
        type="email"
        value={email}
        onChange={(event) => setEmail(event.target.value)}
        onBlur={() => setInvalid(email === '')}
      />
    </Field>
  );
}
